# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: hemisample
      type: github
      endpoint: "github connection 1"
      name: "hemisample"
    - repository: Dummy3183
      type: github
      endpoint: "github connection 1"
      name: "Dummy3183"

stages:
  - stage: Test
    displayName: Test
    jobs:
      - job: Test
        displayName: Test