# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: none
  - script: |
      echo "Hello World!"
      echo "How's it going?"
      echo "Great job!!!"

# stages:
#   - stage: "Dummy"
#     displayName: "Dummy"
#     jobs:
#     - job: "Dummy"
#       displayName: "What's up!"
#       steps:
#       - checkout: none
#       - script: echo "Hello World!"
#     # - job: "Dummy2"
#     #   steps:
#     #   - task: Npm@1
#     #   displayName: "Install npm"
  
#   - stage: "Dummy2"
#     jobs:
#     - job: "Dummy2"
#       displayName: "Nothing much"
#       steps:
#         - script: echo "What's going on!!! "